[profile.default]
src = 'contracts'
out = 'foundry-out'
solc_version = '0.8.20'
optimizer_runs = 800
via_ir = false
ffi = true
fs_permissions = [{ access = "read-write", path = ".forge-snapshots/"}, { access = "read", path = "./foundry-out"}]
fuzz_seed = 0x4444

[profile.ci]
fuzz_runs = 10000

# See more config options https://github.com/foundry-rs/foundry/tree/master/config
